# Generated by Django 5.2 on 2025-05-21 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0003_alter_imagengaleria_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primer_apellido',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primer_nombre',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
