# Generated by Django 5.2 on 2025-05-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0004_remove_cliente_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre_mascota',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='recordatorio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='tipo_documento',
        ),
    ]
