# Generated by Django 5.2 on 2025-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0005_remove_cita_apellido_remove_cita_correo_electronico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Realizada', 'Realizada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
