# Generated by Django 5.2 on 2025-05-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0006_citarapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
