# Generated by Django 5.2 on 2025-05-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0008_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Realizada', 'Realizada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
