# Generated by Django 5.2 on 2025-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0009_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='citarapida',
            name='estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], max_length=20),
        ),
    ]
