# Generated by Django 5.2 on 2025-05-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0010_alter_cita_estado_alter_citarapida_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
