# Generated by Django 5.2 on 2025-05-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0011_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citarapida',
            name='edad_mascota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='citarapida',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='citarapida',
            name='raza_mascota',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
