# Generated by Django 5.2 on 2025-05-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0012_citarapida_edad_mascota_citarapida_nombre_mascota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Apl.mascota'),
        ),
    ]
