# Generated by Django 5.2.1 on 2025-05-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0009_remove_administrador_contraseña_administrador_groups_and_more'),
        ('Apl', '0013_cita_mascota'),
    ]

    operations = [
    ]
