# Generated by Django 5.2.1 on 2025-06-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0014_merge_20250530_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='mostrar_boton_agendar',
        ),
    ]
