# Generated by Django 5.2 on 2025-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0015_remove_servicio_mostrar_boton_agendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='titulo_ventana',
            field=models.CharField(default='Detalles del Servicio', editable=False, max_length=250, verbose_name='Título en ventana'),
        ),
    ]
