# urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('gestion-usuarios/', views.usuarios, name='gestion_usuarios'),
    path('servicios/', views.servicios, name='servicios'),
    path('Agendar/', views.Agendar, name='agendar'),
    path('login/', views.login, name='login'),
    path('Agenadarllamada/', views.llamadacita, name='Agenadarllamada'),
    path('logout/', views.logout, name='logout'),
    path('RecuperarContrasena/', views.RContrasena, name='recuperar_contrasena'),
    path('cambia_contraseña/<str:token>/', views.cambia_con, name='cambia_con'),
    path('recuperarcontrasenaenviado/', views.recuperar_contrasena_enviado, name='RContrasenaenviado'),
    path('Galeria/', views.gestion_galeria, name='Galeria'),
    path('api/galeria/', views.api_galeria, name='api_galeria'),
    path('api/galeria/<int:imagen_id>/', views.api_galeria, name='api_galeria_detail'),
    path('eliminar-imagen/<int:imagen_id>/', views.eliminar_imagen, name='eliminar_imagen'),
    path('Tipdelasemana/', views.gestion_tip, name='Tipdelasemana'),
    path('Gestioncitas/', views.gestion_citas, name='gestioncitas'),
    path('modificaservicio/', views.ModificarS, name='modificarservicio'),
    path('registroCita/', views.RegistroC, name='registroc'),
    path('eliminar-tip/<int:tip_id>/', views.eliminar_tip, name='eliminar_tip'),
    path('obtener-tip-actual/', views.obtener_tip_actual, name='obtener_tip_actual'),
    path('backup/', views.backup, name='backup'),
    path('aceptar-cita/<int:cita_id>/', views.aceptar_cita, name='aceptar_cita'),
    path('rechazar-cita/<int:cita_id>/', views.rechazar_cita, name='rechazar_cita'),
    path('eliminar-cita/<int:cita_id>/', views.eliminar_cita, name='eliminar_cita'),
    path('cambiar-estado-cita/<int:cita_id>/', views.cambiar_estado_cita, name='cambiar_estado_cita'),
    path('editar-observacion-cita/<int:cita_id>/', views.editar_observacion_cita, name='editar_observacion_cita'),
    path('editar_estado_observacion_rapida/<int:cita_id>/', views.editar_estado_observacion_rapida, name='editar_estado_observacion_rapida'),
    path('editar_estado_observacion_normal/<int:cita_id>/', views.editar_estado_observacion_normal, name='editar_estado_observacion_normal'),
    path('Cancelacion/', views.Cancelarcita, name='CancelarCita'),
    path('api/servicios/', views.api_servicios, name='api_servicios'),
    path('api/servicios/<int:servicio_id>/', views.api_servicios, name='api_servicio_detail'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('usuarios/eliminar/<str:documento>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('usuarios/editar/<str:documento>/', views.editar_usuario, name='editar_usuario'),
    path('usuarios/toggle-estado/<str:documento>/', views.toggle_estado_usuario, name='toggle_estado_usuario'),
    path('usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('logout/', views.logout, name='logout'),
    path('reporte-citas-pdf/', views.reporte_citas_pdf, name='reporte_citas_pdf'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
